POST http://localhost:4000/app/sendmessage
Content-Type: application/json

{
    "sender":"12345687",
    "fullName":"test test test test",
    "email":"test1234596789@gmail.com",
    "phone":"0612345679",
    "mess":"I love Pizza"
}